module.exports = {
  operation: {
    perform: {
      url: "https://api.tomba.io/v1/email-count/",
      method: "GET",
      params: { domain: "{{bundle.inputData.domain}}" },
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
        "X-Tomba-Key": "{{bundle.authData.api_key}}",
      },
      body: { domain: "{{bundle.inputData.domain}}" },
      removeMissingValuesFrom: {},
    },
    inputFields: [
      {
        key: "domain",
        label: "Domain",
        type: "string",
        helpText:
          'Domain name from which you want to find the email addresses. For example, "stripe.com".',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      data: {
        total: 0,
        personal_emails: 0,
        generic_emails: 0,
        department: {
          engineering: 0,
          finance: 0,
          hr: 0,
          it: 0,
          marketing: 0,
          operations: 0,
          management: 0,
          sales: 0,
          legal: 0,
          support: 0,
          communication: 0,
        },
        seniority: {
          junior: 0,
          senior: 0,
          executive: 0,
        },
      },
    },
    outputFields: [
      { key: "data__total", type: "integer" },
      { key: "data__personal_emails", type: "integer" },
      { key: "data__generic_emails", type: "integer" },
      { key: "data__department__engineering", type: "integer" },
      { key: "data__department__finance", type: "integer" },
      { key: "data__department__hr", type: "integer" },
      { key: "data__department__it", type: "integer" },
      { key: "data__department__marketing", type: "integer" },
      { key: "data__department__operations", type: "integer" },
      { key: "data__department__management", type: "integer" },
      { key: "data__department__sales", type: "integer" },
      { key: "data__department__legal", type: "integer" },
      { key: "data__department__support", type: "integer" },
      { key: "data__department__communication", type: "integer" },
      { key: "data__seniority__junior", type: "integer" },
      { key: "data__seniority__senior", type: "integer" },
      { key: "data__seniority__executive", type: "integer" },
    ],
  },
  key: "count_email",
  noun: "Count Email",
  display: {
    label: "Count Email",
    description: "Returns total email addresses we have for one domain.",
    hidden: false,
  },
};
