module.exports = {
  operation: {
    perform: {
      url: 'https://api.tomba.io/v1/email-count/',
      method: 'GET',
      params: { domain: '{{bundle.inputData.domain}}' },
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        'X-Tomba-Key': '{{bundle.authData.api_key}}',
      },
      body: { domain: '{{bundle.inputData.domain}}' },
      removeMissingValuesFrom: {},
    },
    inputFields: [
      {
        key: 'domain',
        label: 'Domain',
        type: 'string',
        helpText:
          'Domain name from which you want to find the email addresses. For example, "stripe.com".',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      data: {
        total: 129283,
        personal_emails: 129283,
        generic_emails: 295,
        department: {
          engineering: 871,
          finance: 692,
          hr: 505,
          it: 1040,
          marketing: 4996,
          operations: 2369,
          management: 4208,
          sales: 1455,
          legal: 208,
          support: 1414,
          communication: 226,
        },
        seniority: { junior: 3265, senior: 20948, executive: 4712 },
      },
    },
    outputFields: [
      { key: 'data__total' },
      { key: 'data__personal_emails' },
      { key: 'data__generic_emails' },
      { key: 'data__department__engineering' },
      { key: 'data__department__finance' },
      { key: 'data__department__hr' },
      { key: 'data__department__it' },
      { key: 'data__department__marketing' },
      { key: 'data__department__operations' },
      { key: 'data__department__management' },
      { key: 'data__department__sales' },
      { key: 'data__department__legal' },
      { key: 'data__department__support' },
      { key: 'data__department__communication' },
      { key: 'data__seniority__junior' },
      { key: 'data__seniority__senior' },
      { key: 'data__seniority__executive' },
    ],
  },
  key: 'count_email',
  noun: 'Count',
  display: {
    label: 'Count Email',
    description: 'Returns total email addresses we have for one domain.',
    hidden: false,
    important: true,
  },
};
