const perform = (z, bundle) => {
  const options = {
    url: `https://api.tomba.io/v1/domain-search`,
    method: 'GET',
    headers: {
      'X-Tomba-Key': bundle.authData.api_key,
      'X-Tomba-Secret': bundle.authData.secret_key,
    },
    params: {
      domain: bundle.inputData.domain,
    },
  };

  return z.request(options).then((response) => {
    response.throwForStatus();
    const results = response.json;

    // You can do any parsing you need for results here before returning them

    return [results];
  });
};

module.exports = {
  operation: {
    perform: perform,
    inputFields: [
      {
        key: 'domain',
        label: 'Domain',
        type: 'string',
        helpText: 'Domain name from which you want to find the email addresses',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      data: {
        organization: {
          location: {
            country: 'US',
            city: null,
            state: null,
            street_address: null,
          },
          social_links: {
            twitter_url: 'https://twitter.com/tombaplatforum',
            facebook_url: 'https://www.facebook.com/tombaplatforum',
            linkedin_url: 'https://www.linkedin.com/company/tomba-io',
          },
          disposable: false,
          webmail: false,
          website_url: 'tomba.io',
          phone_number: null,
          industries: 'internet',
          postal_code: null,
          employee_count: 0,
          last_updated: '2021-01-13T15:10:55+01:00',
          revenue: null,
          accept_all: false,
          pattern: '{l}.{first}',
          domain_score: 30,
          organization: 'Tomba',
        },
        emails: [
          {
            email: 'security@tomba.io',
            first_name: null,
            last_name: null,
            full_name: null,
            phone_number: null,
            type: 'generic',
            country: null,
            position: '',
            department: 'security',
            seniority: null,
            twitter: null,
            linkedin: null,
            accept_all: false,
            pattern: '{l}.{first}',
            score: 50,
            verification: { date: null, status: null },
            last_updated: '2021-04-11T19:24:13+01:00',
            sources: [
              {
                uri: 'https://tomba.io/security-bounty-program',
                extracted_on: '2021-03-27 19:37:03',
                last_seen_on: '2021-04-11 15:32:50',
                still_on_page: true,
                website_url: 'tomba.io',
              },
            ],
          },
          {
            email: 'privacy@tomba.io',
            first_name: null,
            last_name: null,
            full_name: null,
            phone_number: null,
            type: 'generic',
            country: null,
            position: null,
            department: null,
            seniority: null,
            twitter: null,
            linkedin: null,
            accept_all: false,
            pattern: '{l}.{first}',
            score: 50,
            verification: { date: null, status: null },
            last_updated: '2021-04-11T19:24:49+01:00',
            sources: [
              {
                uri: 'https://tomba.io/privacy-notice-for-california-residents',
                extracted_on: '2021-03-27 19:37:04',
                last_seen_on: '2021-04-11 15:32:50',
                still_on_page: true,
                website_url: 'tomba.io',
              },
            ],
          },
          {
            email: 'opt-out@tomba.io',
            first_name: null,
            last_name: null,
            full_name: null,
            phone_number: null,
            type: 'personal',
            country: null,
            position: null,
            department: null,
            seniority: null,
            twitter: null,
            linkedin: null,
            accept_all: false,
            pattern: '{l}.{first}',
            score: 50,
            verification: { date: null, status: null },
            last_updated: '2021-04-11T19:24:49+01:00',
            sources: [
              {
                uri: 'https://tomba.io/privacy-notice-for-california-residents',
                extracted_on: '2021-03-27 19:37:04',
                last_seen_on: '2021-04-11 15:32:50',
                still_on_page: true,
                website_url: 'tomba.io',
              },
            ],
          },
          {
            email: 'opt-in@tomba.io',
            first_name: null,
            last_name: null,
            full_name: null,
            phone_number: null,
            type: 'personal',
            country: null,
            position: null,
            department: null,
            seniority: null,
            twitter: null,
            linkedin: null,
            accept_all: false,
            pattern: '{l}.{first}',
            score: 50,
            verification: { date: null, status: null },
            last_updated: '2021-04-11T19:24:49+01:00',
            sources: [
              {
                uri: 'https://tomba.io/privacy-notice-for-california-residents',
                extracted_on: '2021-03-27 19:37:04',
                last_seen_on: '2021-04-11 15:32:50',
                still_on_page: true,
                website_url: 'tomba.io',
              },
            ],
          },
          {
            email: 'dev@tomba.io',
            first_name: null,
            last_name: null,
            full_name: null,
            phone_number: null,
            type: 'generic',
            country: null,
            position: null,
            department: null,
            seniority: null,
            twitter: null,
            linkedin: null,
            accept_all: false,
            pattern: '{l}.{first}',
            score: 50,
            verification: { date: null, status: null },
            last_updated: '2021-02-08T22:43:22+01:00',
            sources: [
              {
                uri:
                  'https://tomba-io.github.io/generic-emails/classes/emails.html',
                extracted_on: '2021-02-08 20:02:54',
                last_seen_on: '2021-02-08 22:43:22',
                still_on_page: true,
                website_url: 'tomba-io.github.io',
              },
            ],
          },
          {
            email: 'info@tomba.io',
            first_name: null,
            last_name: null,
            full_name: null,
            phone_number: null,
            type: 'generic',
            country: null,
            position: null,
            department: 'communication',
            seniority: null,
            twitter: null,
            linkedin: null,
            accept_all: false,
            pattern: '{l}.{first}',
            score: 50,
            verification: { date: null, status: null },
            last_updated: '2021-03-13T01:12:28+01:00',
            sources: [
              {
                uri:
                  'https://tomba-io.github.io/generic-emails/classes/genericemail.html',
                extracted_on: '2021-02-08 20:02:55',
                last_seen_on: '2021-02-08 22:43:22',
                still_on_page: true,
                website_url: 'tomba-io.github.io',
              },
            ],
          },
          {
            email: 'support@tomba.io',
            first_name: null,
            last_name: null,
            full_name: null,
            phone_number: null,
            type: 'generic',
            country: null,
            position: null,
            department: 'support',
            seniority: null,
            twitter: null,
            linkedin: null,
            accept_all: false,
            pattern: '{l}.{first}',
            score: 50,
            verification: { date: null, status: null },
            last_updated: '2021-03-13T02:03:14+01:00',
            sources: [
              {
                uri: 'https://tomba.io/pricing',
                extracted_on: '2021-02-08 20:07:29',
                last_seen_on: '2021-04-11 15:32:50',
                still_on_page: true,
                website_url: 'tomba.io',
              },
              {
                uri: 'https://tomba.io/about',
                extracted_on: '2021-02-08 20:07:29',
                last_seen_on: '2021-04-11 15:32:50',
                still_on_page: true,
                website_url: 'tomba.io',
              },
            ],
          },
          {
            email: 'press@tomba.io',
            first_name: null,
            last_name: null,
            full_name: null,
            phone_number: null,
            type: 'generic',
            country: null,
            position: null,
            department: 'communication',
            seniority: null,
            twitter: null,
            linkedin: null,
            accept_all: false,
            pattern: '{l}.{first}',
            score: 50,
            verification: { date: null, status: null },
            last_updated: '2021-03-13T01:12:28+01:00',
            sources: [
              {
                uri: 'https://tomba.io/press',
                extracted_on: '2021-02-08 20:07:29',
                last_seen_on: '2021-04-11 15:32:50',
                still_on_page: true,
                website_url: 'tomba.io',
              },
            ],
          },
          {
            email: 'b.mohamed@tomba.io',
            first_name: 'Mohamed',
            last_name: 'Ben rebia',
            full_name: 'Mohamed Ben rebia',
            phone_number: null,
            type: 'personal',
            country: 'DZ',
            position: 'ceo',
            department: 'executive',
            seniority: 'senior',
            twitter: null,
            linkedin: 'https://www.linkedin.com/in/mohamed-ben-rebia-4337061ba',
            accept_all: false,
            pattern: '{l}.{first}',
            score: 90,
            verification: { date: null, status: null },
            last_updated: '2021-03-13T01:19:14+01:00',
            sources: [
              {
                uri:
                  'https://github.com/tomba-io/generic-emails/blob/084fc1a63d3cdaf9a34f255bedc2baea49a8e8b9/src/lib/validation/hash.ts',
                extracted_on: '2021-02-08 20:09:54',
                last_seen_on: '2021-02-08 22:43:40',
                still_on_page: true,
                website_url: 'github.com',
              },
              {
                uri:
                  'https://github.com/tomba-io/generic-emails/blame/084fc1a63d3cdaf9a34f255bedc2baea49a8e8b9/src/lib/validation/hash.ts',
                extracted_on: '2021-02-08 20:09:59',
                last_seen_on: '2021-02-08 22:43:40',
                still_on_page: true,
                website_url: 'github.com',
              },
            ],
          },
          {
            email: 'b.abedrahim@tomba.io',
            first_name: 'Abedrahim',
            last_name: 'Ben rebia',
            full_name: 'Abedrahim Ben rebia',
            phone_number: null,
            type: 'personal',
            country: 'DZ',
            position: 'ceo',
            department: 'executive',
            seniority: 'senior',
            twitter: null,
            linkedin:
              'https://www.linkedin.com/in/abedrahim-ben-rebia-b7a757203',
            accept_all: false,
            pattern: '{l}.{first}',
            score: 90,
            verification: { date: null, status: null },
            last_updated: '2021-03-13T01:19:14+01:00',
            sources: [
              {
                uri:
                  'https://github.com/tomba-io/generic-emails/blob/084fc1a63d3cdaf9a34f255bedc2baea49a8e8b9/src/lib/validation/hash.ts',
                extracted_on: '2021-02-08 20:09:54',
                last_seen_on: '2021-02-08 22:43:40',
                still_on_page: true,
                website_url: 'github.com',
              },
              {
                uri:
                  'https://github.com/tomba-io/generic-emails/blame/084fc1a63d3cdaf9a34f255bedc2baea49a8e8b9/src/lib/validation/hash.ts',
                extracted_on: '2021-02-08 20:09:59',
                last_seen_on: '2021-02-08 22:43:40',
                still_on_page: true,
                website_url: 'github.com',
              },
            ],
          },
        ],
      },
      meta: { total: 11, pageSize: 10, current: 0, total_pages: 2 },
    },
    outputFields: [
      { key: 'data__organization__location__country' },
      { key: 'data__organization__location__city' },
      { key: 'data__organization__location__state' },
      { key: 'data__organization__location__street_address' },
      { key: 'data__organization__social_links__twitter_url' },
      { key: 'data__organization__social_links__facebook_url' },
      { key: 'data__organization__social_links__linkedin_url' },
      { key: 'data__organization__disposable' },
      { key: 'data__organization__webmail' },
      { key: 'data__organization__website_url' },
      { key: 'data__organization__phone_number' },
      { key: 'data__organization__industries' },
      { key: 'data__organization__postal_code' },
      { key: 'data__organization__employee_count' },
      { key: 'data__organization__last_updated' },
      { key: 'data__organization__revenue' },
      { key: 'data__organization__accept_all' },
      { key: 'data__organization__pattern' },
      { key: 'data__organization__domain_score' },
      { key: 'data__organization__organization' },
      { key: 'data__emails[]email' },
      { key: 'data__emails[]first_name' },
      { key: 'data__emails[]last_name' },
      { key: 'data__emails[]full_name' },
      { key: 'data__emails[]phone_number' },
      { key: 'data__emails[]type' },
      { key: 'data__emails[]country' },
      { key: 'data__emails[]position' },
      { key: 'data__emails[]department' },
      { key: 'data__emails[]seniority' },
      { key: 'data__emails[]twitter' },
      { key: 'data__emails[]linkedin' },
      { key: 'data__emails[]accept_all' },
      { key: 'data__emails[]pattern' },
      { key: 'data__emails[]score' },
      { key: 'data__emails[]verification__date' },
      { key: 'data__emails[]verification__status' },
      { key: 'data__emails[]last_updated' },
      { key: 'data__emails[]sources[]uri' },
      { key: 'data__emails[]sources[]extracted_on' },
      { key: 'data__emails[]sources[]last_seen_on' },
      { key: 'data__emails[]sources[]still_on_page' },
      { key: 'data__emails[]sources[]website_url' },
      { key: 'meta__total' },
      { key: 'meta__pageSize' },
      { key: 'meta__current' },
      { key: 'meta__total_pages' },
    ],
  },
  key: 'domain_search',
  noun: 'Domain',
  display: {
    label: 'Domain Search',
    description: 'Give domain and it returns all the email addresses.',
    hidden: false,
    important: true,
  },
};
